baseURL = 'https://icysamon.github.io/'
languageCode = 'ja-jp'
title = '水深７メートル'
theme = 'chord'
defaultContentLanguage = "ja"

[permalinks]
  post = '/post/:year/:month/:slug/'
  page = '/:slug/'

[module]
  [module.hugoVersion]
    extended = true
    min = '0.146.0'

[menus]
  [[menus.main]]
    name = 'ホーム'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = '利用規約'
    pageRef = '/page/terms-of-service/'
    weight = 20
  
  [[menus.main]]
    name = 'サイトについて'
    pageRef = '/page/about/'
    weight = 30

[assets]
  favicon = '/favicon.ico'

[params]
  year = '2025'
  copyright = 'icysamon'
  homepageurl = 'https://icysamon.com'
  subtitle = 'フリーBGM'
  image = 'https://image.icysamon.com/avatar/artist.webp'

